### ISSUE TITLE
plot_code format ALP-01

### ISSUE THREAD

**Issue by cecilegirardin** [OxfordEcosystemsLab/gemdata#10]
Please make sure that the plot_code format is three characters, dash, two numerics. 
Thank you,
Cécile

**Comment by edgeeffect** [comment]
The importers will now accept plot codes in AAA-999 and AAA999 format

**Comment by edgeeffect** [comment]
I've currently only half-done this it seems.
I've made it so that both formats are allowable by the importers
But I've still got it in the no-hyphen format it the database.

**Comment by edgeeffect** [comment]
Fixed it now. Either format can be imported - but the hyphened format is stored.
