### ISSUE TITLE
Need to accept GEM traits trees

### ISSUE THREAD

**Issue by bdvholmes** [OxfordEcosystemsLab/gemdata#7]
E.g. with a tree code `ESP01-I2005`. There should be some kind of flag in the DB to acknowledge that it's a GEM traits tree not a GEM carbon one.

**Comment by edgeeffect** [comment]
we now have a column in the trees table called gem_trees

it's true by default - and therefore true for forest plots T999 trees
during import of the I999 trees it's explicity set to false
